"""add not null for like

Revision ID: 02a66ce10ccf
Revises: c72d25f1b117
Create Date: 2019-09-21 16:08:08.720513

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '02a66ce10ccf'
down_revision = 'c72d25f1b117'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('likes', 'author_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('likes', 'post_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('likes', 'post_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('likes', 'author_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
