"""add like label post

Revision ID: 253f24bce4d8
Revises: 02a66ce10ccf
Create Date: 2019-09-21 17:25:20.376138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '253f24bce4d8'
down_revision = '02a66ce10ccf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('like_label', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'like_label')
    # ### end Alembic commands ###
