"""initial migration

Revision ID: 6be20348d404
Revises: 
Create Date: 2019-09-20 06:38:22.109962

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '6be20348d404'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(length=256), nullable=True),
                    sa.Column('name', sa.String(length=64), nullable=True),
                    sa.Column('phone_number', sa.String(length=16), nullable=True),
                    sa.Column('occupation', sa.String(length=64), nullable=True),
                    sa.Column('member_from', sa.String(length=16), nullable=True),
                    sa.Column('member_since', sa.DateTime(), nullable=True),
                    sa.Column('has_enough_info', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
