"""empty message

Revision ID: f18171d94c13
Revises: 253f24bce4d8
Create Date: 2019-09-21 17:28:17.881123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f18171d94c13'
down_revision = '253f24bce4d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('like_label', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'like_label')
    # ### end Alembic commands ###
